
name: Odometer and Service Perimeter Update

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt || echo "No dependencies"

      - name: Run Odometer Script
        run: python OdometerToFluke.py  # Make sure this matches your script name
        env:
          SANDBOX_KEY: ${{ secrets.SANDBOX_KEY }}
          PRODUCTION_KEY: ${{ secrets.PRODUCTION_KEY }}
          MOTIVE_KEY: ${{ secrets.MOTIVE_KEY }}
      
      - name: Run Service Perimeter Script
        run: python ServicePerimeterUpdate.py  # Make sure this matches your script name
        env:
          SANDBOX_KEY: ${{ secrets.SANDBOX_KEY }}
          PRODUCTION_KEY: ${{ secrets.PRODUCTION_KEY }}
          MOTIVE_KEY: ${{ secrets.MOTIVE_KEY }}


